webtalk_init -webtalk_dir F:/ITMO/course_4/io_systems/lab_2/lab_2.sim/sim_1/behav/xsim/xsim.dir/sim_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Dec 12 21:37:40 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018833" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "da794992-3ee2-403f-b1c1-f2c293e21fdd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c31246ea606b4926bb4d055d4957d28e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD FX(tm)-4100 Quad-Core Processor            " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3624 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "53865100 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "24" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "4.87_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15388_KB" -context "xsim\\usage"
webtalk_transmit -clientid 476598947 -regid "" -xml F:/ITMO/course_4/io_systems/lab_2/lab_2.sim/sim_1/behav/xsim/xsim.dir/sim_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html F:/ITMO/course_4/io_systems/lab_2/lab_2.sim/sim_1/behav/xsim/xsim.dir/sim_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm F:/ITMO/course_4/io_systems/lab_2/lab_2.sim/sim_1/behav/xsim/xsim.dir/sim_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
