SET SERVEROUTPUT ON FORMAT WRAPPED; # Is needed for server output, without it it's empty

DECLARE
  TAB_NAME VARCHAR2(30) := 'TABLIZA';
  CURSOR CURSY IS SELECT * FROM ALL_TRIGGERS;
BEGIN
  DBMS_OUTPUT.PUT_LINE('COLUMN NAME    TRIGGER NAME');
  FOR COLM IN CURSY
  LOOP
    IF COLM.TABLE_NAME = TAB_NAME THEN
      DBMS_OUTPUT.PUT_LINE(COLM.COLUMN_NAME||'    '||COLM.TRIGGER_NAME);
    END IF;
  END LOOP;
END;
/
