/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sigma' at '10/7/16 3:19 PM' with Gradle 2.10
 *
 * @author sigma, @date 10/7/16 3:19 PM
 */
public class Main {
    public static void main(String[] args) {
        System.out.println("Hello world!");
    }
}
